import javax.swing.*;
import java.awt.*;

/**
 * Created by IntelliJ IDEA.
 * User: Dominik
 * Date: 28.10.2010
 * Time: 18:53:26
 */
public class GameForm {
  private JMenuBar menuBar;
  private JPanel panel1;
  private JButton b4;
  private JButton b3;
  private JButton a1;
  private JButton b5;
  private JButton a2;
  private JButton button4;
  private JButton button8;
  private JButton b2;
  private JButton button10;
  private JButton b1;
  private JButton button12;
  private JButton b6;
  private JTextPane status;

  public GameForm() {
    menuBar = new JMenuBar();
    JMenu gameMenu = new JMenu("Game");
    gameMenu.add(new JMenuItem("Exit"));
    menuBar.add(gameMenu);
  }

  public static void main(String[] args) {
    JFrame frame = new JFrame("Game Form");
    GameForm form = new GameForm();
    frame.getContentPane().add(form.$$$getRootComponent$$$());
    frame.setJMenuBar(form.getMenuBar());
    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    frame.pack();
    frame.setVisible(true);
  }

  public JMenuBar getMenuBar() {
    return menuBar;
  }

  {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
    $$$setupUI$$$();
  }

  /**
   * Method generated by IntelliJ IDEA GUI Designer
   * >>> IMPORTANT!! <<<
   * DO NOT edit this method OR call it in your code!
   *
   * @noinspection ALL
   */
  private void $$$setupUI$$$() {
    panel1 = new JPanel();
    panel1.setLayout(new BorderLayout(0, 0));
    final JPanel panel2 = new JPanel();
    panel2.setLayout(new GridBagLayout());
    panel1.add(panel2, BorderLayout.CENTER);
    b4 = new JButton();
    b4.setText("4");
    GridBagConstraints gbc;
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 0;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    panel2.add(b4, gbc);
    b3 = new JButton();
    b3.setText("4");
    gbc = new GridBagConstraints();
    gbc.gridx = 3;
    gbc.gridy = 0;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    panel2.add(b3, gbc);
    a1 = new JButton();
    a1.setText("4");
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 1;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    panel2.add(a1, gbc);
    b5 = new JButton();
    b5.setText("4");
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 0;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    panel2.add(b5, gbc);
    a2 = new JButton();
    a2.setText("4");
    gbc = new GridBagConstraints();
    gbc.gridx = 1;
    gbc.gridy = 1;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    panel2.add(a2, gbc);
    button4 = new JButton();
    button4.setText("4");
    gbc = new GridBagConstraints();
    gbc.gridx = 2;
    gbc.gridy = 1;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    panel2.add(button4, gbc);
    button8 = new JButton();
    button8.setText("4");
    gbc = new GridBagConstraints();
    gbc.gridx = 3;
    gbc.gridy = 1;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    panel2.add(button8, gbc);
    b2 = new JButton();
    b2.setText("4");
    gbc = new GridBagConstraints();
    gbc.gridx = 4;
    gbc.gridy = 0;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    panel2.add(b2, gbc);
    button10 = new JButton();
    button10.setText("4");
    gbc = new GridBagConstraints();
    gbc.gridx = 4;
    gbc.gridy = 1;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    panel2.add(button10, gbc);
    b1 = new JButton();
    b1.setText("4");
    gbc = new GridBagConstraints();
    gbc.gridx = 5;
    gbc.gridy = 0;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    panel2.add(b1, gbc);
    button12 = new JButton();
    button12.setText("4");
    gbc = new GridBagConstraints();
    gbc.gridx = 5;
    gbc.gridy = 1;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    panel2.add(button12, gbc);
    b6 = new JButton();
    b6.setText("4");
    b6.putClientProperty("html.disable", Boolean.FALSE);
    b6.putClientProperty("hideActionText", Boolean.FALSE);
    gbc = new GridBagConstraints();
    gbc.gridx = 0;
    gbc.gridy = 0;
    gbc.fill = GridBagConstraints.HORIZONTAL;
    panel2.add(b6, gbc);
    final JPanel panel3 = new JPanel();
    panel3.setLayout(new BorderLayout(0, 0));
    panel1.add(panel3, BorderLayout.NORTH);
    final JPanel panel4 = new JPanel();
    panel4.setLayout(new BorderLayout(0, 0));
    panel1.add(panel4, BorderLayout.SOUTH);
    status = new JTextPane();
    status.setText("It is Alice's turn");
    panel4.add(status, BorderLayout.CENTER);
  }

  /**
   * @noinspection ALL
   */
  public JComponent $$$getRootComponent$$$() {
    return panel1;
  }
}
